logging:
  level:
    org.springframework: INFO

server:
  port: 8080
  contextPath: "/notification"

spring:
  liquibase:
    enabled: false
  jackson:
    serialization-inclusion: non_null

kafka:
  topics:
    - name: "messages"
      brokers:
        - "localhost:9092"
      group: "text_topic_group"
      keyDeserializer: "org.apache.kafka.common.serialization.LongDeserializer"
      valueDeserializer: "pro.ambulando.slack.notifier.kafka.MessageDeserializer"
